In [20]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Bidirectional, LSTM, Dropout, Dense
from keras.optimizers import Adam
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from keras.regularizers import l2
import matplotlib.pyplot as plt
from keras.preprocessing.sequence import TimeseriesGenerator
import datetime as dt
# Check current directory
import os
print(os.getcwd())

/Users/sethblum/Library/CloudStorage/OneDrive-MassachusettsInstituteofTechnology/Courses/1C51/project-repo/FinalProject_1.C01


In [21]:
## Should change this to be an import

def rev_encode_data(X, y, lookback = 96, forecast=96):
    """
    Encode the data for training an LSTM model, including creating sequences and splitting into input and target.

    Parameters:
    X (numpy.ndarray): The input data array.
    y (numpy.ndarray): The target variable array.
    lookback (int): The number of timesteps to look back (48 hours with 15 minute intervals).
    forecast (int): The number of timesteps to forecast (24 hours with 15 minute intervals).

    Returns:
    X_seq (numpy.ndarray): The encoded input data with sequences.
    y_seq (numpy.ndarray): The encoded target variable array with sequences.
    """

    if len(X) != len(y):
        raise ValueError("X and y must have the same length.")
    l = lookback
    f = forecast
    X_seq = []
    y_seq = []

    for i in range(len(X) - l - f + 1):
        Xtemp = X[i:i+l+f]
        ytemp = y[i+l:i+l+f]
        X_seq.append(Xtemp)
        y_seq.append(ytemp)
        if i % 500 == 0:
            print(i)

    return np.array(X_seq), np.array(y_seq)


# Encode the train and test data


In [22]:
X = np.reshape(np.arange(0,200),(100,2))
y = np.arange(200,300)

In [23]:
X_seq, y_seq = rev_encode_data(X, y, lookback = 5, forecast=5)

0


In [24]:
X_seq

array([[[  0,   1],
        [  2,   3],
        [  4,   5],
        ...,
        [ 14,  15],
        [ 16,  17],
        [ 18,  19]],

       [[  2,   3],
        [  4,   5],
        [  6,   7],
        ...,
        [ 16,  17],
        [ 18,  19],
        [ 20,  21]],

       [[  4,   5],
        [  6,   7],
        [  8,   9],
        ...,
        [ 18,  19],
        [ 20,  21],
        [ 22,  23]],

       ...,

       [[176, 177],
        [178, 179],
        [180, 181],
        ...,
        [190, 191],
        [192, 193],
        [194, 195]],

       [[178, 179],
        [180, 181],
        [182, 183],
        ...,
        [192, 193],
        [194, 195],
        [196, 197]],

       [[180, 181],
        [182, 183],
        [184, 185],
        ...,
        [194, 195],
        [196, 197],
        [198, 199]]])

In [25]:
y_seq

# so bc of the lack of lookback in the y data, the data is misaligned unless we do something about it

array([[205, 206, 207, 208, 209],
       [206, 207, 208, 209, 210],
       [207, 208, 209, 210, 211],
       [208, 209, 210, 211, 212],
       [209, 210, 211, 212, 213],
       [210, 211, 212, 213, 214],
       [211, 212, 213, 214, 215],
       [212, 213, 214, 215, 216],
       [213, 214, 215, 216, 217],
       [214, 215, 216, 217, 218],
       [215, 216, 217, 218, 219],
       [216, 217, 218, 219, 220],
       [217, 218, 219, 220, 221],
       [218, 219, 220, 221, 222],
       [219, 220, 221, 222, 223],
       [220, 221, 222, 223, 224],
       [221, 222, 223, 224, 225],
       [222, 223, 224, 225, 226],
       [223, 224, 225, 226, 227],
       [224, 225, 226, 227, 228],
       [225, 226, 227, 228, 229],
       [226, 227, 228, 229, 230],
       [227, 228, 229, 230, 231],
       [228, 229, 230, 231, 232],
       [229, 230, 231, 232, 233],
       [230, 231, 232, 233, 234],
       [231, 232, 233, 234, 235],
       [232, 233, 234, 235, 236],
       [233, 234, 235, 236, 237],
       [234, 2

In [26]:
X_seq

array([[[  0,   1],
        [  2,   3],
        [  4,   5],
        ...,
        [ 14,  15],
        [ 16,  17],
        [ 18,  19]],

       [[  2,   3],
        [  4,   5],
        [  6,   7],
        ...,
        [ 16,  17],
        [ 18,  19],
        [ 20,  21]],

       [[  4,   5],
        [  6,   7],
        [  8,   9],
        ...,
        [ 18,  19],
        [ 20,  21],
        [ 22,  23]],

       ...,

       [[176, 177],
        [178, 179],
        [180, 181],
        ...,
        [190, 191],
        [192, 193],
        [194, 195]],

       [[178, 179],
        [180, 181],
        [182, 183],
        ...,
        [192, 193],
        [194, 195],
        [196, 197]],

       [[180, 181],
        [182, 183],
        [184, 185],
        ...,
        [194, 195],
        [196, 197],
        [198, 199]]])